### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Ystartff** [gentlefress/MLIP#1]
Your paper in very excellent and would like to know when your code will be open source?

**Comment by gentlefress** [comment]
Thank you for your attention. And  I will release the code next weekend.

**Comment by Ystartff** [comment]
I noticed that your paper does not mention the model and number of graphics cards used, could you please advise?

**Comment by gentlefress** [comment]
I trained using four NVIDIA GeForce RTX 3090 graphics cards, each with 24GB of video memory. And for test, one card is sufficient.

**Comment by Ystartff** [comment]
Thank you for your reply, I can't thank you enough. I wish you a happy life and all the best!

**Comment by Markin-Wang** [comment]
Hi, thank you for you work. May I ask any update for the code?

**Comment by gentlefress** [comment]
Thanks for the attention. I am a bit occupied these days and may update in August.

**Comment by Markin-Wang** [comment]
> Thanks for the attention. I am a bit occupied these days and may update in August.

Thank you for your reply. May I ask the details about how you calculate the AUC score for the zero-shot classification. Specificaly, the AUC score requires the probability as input and different ways to calculate the probability could give different results, how the probability is obtained? is it obainted by regarding the similarities as the probability? Also, could you provide the accuracy of the zero-shot calssification for better comparison to previous works.

Thanks for your kind help.

**Comment by Markin-Wang** [comment]
Hi, which pretrained backbone (ViT or ResNet) you used in the reported image-to-text retrieval results?

**Comment by Markin-Wang** [comment]
> Thanks for the attention. I am a bit occupied these days and may update in August.

Hi, any update? thank you,

**Comment by Markin-Wang** [comment]
> > Thanks for the attention. I am a bit occupied these days and may update in August.
> 
> Thank you for your reply. May I ask the details about how you calculate the AUC score for the zero-shot classification. Specificaly, the AUC score requires the probability as input and different ways to calculate the probability could give different results, how the probability is obtained? is it obainted by regarding the similarities as the probability? Also, could you provide the accuracy of the zero-shot calssification for better comparison to previous works.
> 
> Thanks for your kind help.

Hi, I am grateful if you could provide any response to this and also the update for the code. It has been about half a year since the announcement of the CVPR results. Thank you.

**Comment by ustcjinggg** [comment]
Come on man, its already CVPR2025, keep your word

**Comment by Markin-Wang** [comment]
> Come on man, its already CVPR2025, keep your word

Now it's already CVPR2026...
